### ISSUE TITLE
Multiple Sprite Sheets

### ISSUE THREAD

**Issue by mrisney** [IceCreamYou/Canvas-Sprite-Animations#2]
Requesting an example, and more documentation, on how to switch from one sprite sheet to another  during an animation.

See example here : 
http://mrisney.com/sprite-animation/index.html

Thank you.

**Comment by IceCreamYou** [comment]
You should use a different `Sprite` or `SpriteMap` object for each sprite sheet. If you want to display a different animation, just draw the relevant object. For your example, you should probably have one sprite sheet for each person type (skateboarder, snowboarder, and skier) each with three animation sequences (trick one, trick two, and crash). Then track the "active" object and animation with variables (assign them to the correct object when a button is clicked). In your animation loop just draw the active object.

**Comment by intelligence** [comment]
@IceCreamYou I'm using your awesome script to animate video on iOS devices. I'm facing a problem where the sprite is too large (48990x240) for Safari to handle, so it just cuts it off (and for some reason it shows two animations besides each other, it might come out of the iOS max image width restriction, but not sure) leaving a white frame until it loops again. My immediate thought was to split up the sprite into two spritesheets, any idea how to achieve (jumping back and forth from two spritesheets for the same canvas) this with fluid playback? 

Demo:
http://jsbin.com/tojeyagesiku/1/

Edit: Multiple lines in the spritesheet is no solution either, as the iOS is limiting based on megapixels. (www.williammalone.com/articles/html5-javascript-ios-maximum-image-size/)

**Comment by IceCreamYou** [comment]
Basically what you'd want to do is just switch which Sprite(Map) you draw after the first one's animation finishes. For example you could have an array of Sprite(Map)s and a variable that points to the "active" one, and draw the "active" one in your event loop. You could figure out when animations finish (so that you can switch the "active" object) in two different ways:
- Use a timer to wait until the first animation is done
- Advance the animation's frames manually and switch after the relevant number of frames have been displayed. You can do this by setting `useTimer` to false, and then every time you call draw() the current frame will advance by one.

I'd also accept a PR for an option to run a callback (or maybe issue an event, although that might cause stutter as events don't fire immediately) when the animation completes.

**Comment by intelligence** [comment]
Thanks so much for quick input! 

It definitely sounds like it could work. I'm pretty useless with Javascript and logic. If you have any time to spare I would be super grateful if you could show what you mean with some pseudo code?

**Comment by IceCreamYou** [comment]
> I'm pretty useless with Javascript and logic.

Then you're going to have a bad time :smile:

``` javascript
var animations = [
    new Sprite('1.png', {useTimer: false}),
    new Sprite('2.png', {useTimer: false})
];
var activeSprite = animations[0];
var framesDrawn = 0;

function mainLoop() {
    activeSprite.draw(context, 100, 100);
    framesDrawn++;
    if (framesDrawn > 100) activeSprite = animations[1];
}
```

**Comment by intelligence** [comment]
Thanks alot! Super helpful. I'm usually having a bad time, but after some hours of trying and failing I get it right.

I've landed in this so far:

```
var context = document.getElementsByClassName('canvas');
context = context[0].getContext('2d');

var sprites = [
  new Sprite('sprite1.jpg', { frameW: 426, frameH: 240, interval: 23.97, useTimer: false }),
  new Sprite('sprite2.jpg', { frameW: 426, frameH: 240, interval: 23.97, useTimer: false }),
  new Sprite('sprite3.jpg', { frameW: 426, frameH: 240, interval: 23.97, useTimer: false })
];

var activeSprite = sprites[0];
var framesDrawn = 0;

function animate() {
  framesDrawn++;
  activeSprite.draw(context, 0, 0);
  setTimeout(animate, 1000 / 23.97);

  if(framesDrawn>49) {
    activeSprite = sprites[1];
  } 

  if(framesDrawn>99) {
    activeSprite = sprites[2];
  } 

  if(framesDrawn > 114) {
    activeSprite = sprites[0];
    framesDrawn = 0;
  }
}

setTimeout(animate, 150);
```

Any ideas for improvements? In my case it can be any numbers of sprites present, all from 1-5 really, and I guess the amount of frames in them could vary aswell..

**Comment by IceCreamYou** [comment]
In the future, please open a separate issue for something like this. Since we're already here though...

As with most things you write out by hand, you could make it simpler with the right data structure. For example you could have an array of objects that look like `{image: 'sprite1.jpg', frames: 49}`.

Also, you should use `window.requestAnimationFrame()` to power your animate function (like in the index.html that comes with this project) rather than a setTimeout() at 23.97 milliseconds. This will cause your frames to get painted when the browser is ready.
